type Gray = Uint8Array | Buffer | number[];
type Manifest = {format: {fps: number}; scenes: {durationSeconds: number}[]};
export type Jump = {at: number; kind: 'snap' | 'flicker'; difference: number; around: number};
export declare const meanDifference: (a: Gray, b: Gray) => number;
export declare const neighbourDifferences: (frames: Gray[]) => number[];
export declare const sceneStarts: (manifest: Manifest) => {index: number; start: number; end: number}[];
export declare const EXIT_FRAMES: number;
export declare const busiestWindow: (manifest: Manifest, scan: {frame: number; gray: Gray}[], length?: number, cuts?: number[]) => {start: number; motion: number};
export declare const SCAN_FLOOR: number;
export declare const SUDDEN_SCORE: number;
export declare const SUDDEN_WINDOWS: number;
export declare const suddenWindows: (manifest: Manifest, scan: {frame: number; gray: Gray}[], options?: {cuts?: number[]; count?: number; length?: number}) => {start: number; motion: number; score: number}[];
export declare const STRIP_LENGTH: number;
export declare const JUMP_RATIO: number;
export declare const JUMP_FLOOR: number;
export declare const findJumps: (differences: number[], options?: {ratio?: number; floor?: number}) => Jump[];
export declare const determinismFrames: (manifest: Manifest, windowStart: number, length?: number) => number[];
export declare const NOISE_LEVEL: number;
export declare const MAX_CHANGED_SHARE: number;
export declare const renderDifference: (a: Gray, b: Gray) => {changedShare: number; largest: number; alike: boolean};
